[package]
authors = ["Marcel Müller <neikos@neikos.email>"]
name = "antikoerper"
version = "0.2.0"
license = "GPL-3.0"
homepage = "https://github.com/anti-koerper/antikoerper"
keywords = ["monitoring", "lightweight", "fast"]
description = "A lightweight and simple to use local monitoring application"

[dependencies]
clap = "2.1.2"
env_logger = "0.3.2"
log = "0.3.5"
rustc-serialize = "0.3.18"
time = "0.1.34"
toml = "0.1.27"
xdg = "2.0.0"
